---
# tasks file for sorensj.nfs

# Include variables and define needed variables.
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- name: Setup for RedHat/Debian OS family
  ansible.builtin.include_tasks: setup-{{ ansible_os_family }}.yml

# Do not create mountpoint using file, the mount module will create it
# automatically. This avoids problems where the module tries to change
# permissions on an existing directory

- name: Mount NFS share
  become: true
  ansible.posix.mount:
    fstype: "{{ item.nfs_version | default(nfs_version) }}"
    name: "{{ item.path }}"
    opts: "{{ item.opts | default(nfs_mount_opts) }}"
    src: "{{ item.location }}"
    state: mounted
  with_items: "{{ nfs_share_mounts }}"
